
name: Deploy

on:
  push:
    branches: [ "main" ]
  
jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build -t choudhuryshahzad5068/next-js-app .
    - run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
    - run: docker push choudhuryshahzad5068/next-js-app